name: 'hpf_analytics'
version: '1.0.0'
config-version: 2

profile: 'hpf_platform'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  hpf_analytics:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
